name: Build
on:
  push: null
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
    - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1
  build:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
    - name: Install dependencies
      run: python -m pip install -U "jupyterlab>=4.0.0,<5"
    - name: Install R
      uses: r-lib/actions/setup-r@v2
    - name: Install R formatters
      run: Rscript -e 'install.packages(c("styler", "formatR"))'
    - name: Lint the extension
      run: 'set -eux

        jlpm

        jlpm run lint:check

        '
    - name: Test the extension
      run: 'set -eux

        jlpm run test

        '
    - name: Build the extension
      run: 'set -eux

        python -m pip install .[test]


        pytest -vv -r ap --cov jupyterlab_code_formatter

        jupyter server extension list

        jupyter server extension list 2>&1 | grep -ie "jupyterlab_code_formatter.*OK"


        jupyter labextension list

        jupyter labextension list 2>&1 | grep -ie "jupyterlab_code_formatter.*OK"

        python -m jupyterlab.browser_check

        '
    - name: Package the extension
      run: 'set -eux


        pip install build

        python -m build

        pip uninstall -y "jupyterlab_code_formatter" jupyterlab

        '
      id: _bre_build
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: x64
    - name: Install and Test
      run: 'set -eux

        # Remove NodeJS, twice to take care of system and locally installed node versions.

        sudo rm -rf $(which node)

        sudo rm -rf $(which node)


        pip install "jupyterlab>=4.0.0,<5" jupyterlab_code_formatter*.whl



        jupyter server extension list

        jupyter server extension list 2>&1 | grep -ie "jupyterlab_code_formatter.*OK"


        jupyter labextension list

        jupyter labextension list 2>&1 | grep -ie "jupyterlab_code_formatter.*OK"

        python -m jupyterlab.browser_check --no-chrome-test

        '
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Install the extension
      run: 'set -eux

        python -m pip install "jupyterlab>=4.0.0,<5" jupyterlab_code_formatter*.whl

        '
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Install dependencies
      working-directory: ui-tests
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      run: jlpm install
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Set up browser cache
      uses: actions/cache@v4
      with:
        path: '${{ github.workspace }}/pw-browsers

          '
        key: ${{ runner.os }}-${{ hashFiles('ui-tests/yarn.lock') }}
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Install browser
      run: jlpm playwright install chromium
      working-directory: ui-tests
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Execute integration tests
      working-directory: ui-tests
      run: 'jlpm playwright test

        '
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Upload Playwright Test report
      if: (!cancelled() && steps._bre_build.conclusion == 'success') && (always())
      uses: actions/upload-artifact@v4
      with:
        name: jupyterlab_code_formatter-playwright-tests
        path: 'ui-tests/test-results

          ui-tests/playwright-report

          '
